name: Validate Web

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: cd shared && bun install
      - run: cd web && bun install

      - run: bunx graphql-codegen
        working-directory: web

      - name: Lint
        run: bunx eslint web/

      - name: Format check
        run: bunx prettier --check "web/"

      - name: Typecheck
        run: bun run typecheck
        working-directory: web

      - name: Test
        run: bun run test
        working-directory: web

      - name: Build
        run: bun run build
        working-directory: web
